name: friendfy
description: "Friendify"

version: 1.2.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  http: ^1.5.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  riverpod: ^3.0.3
  flutter_riverpod: ^3.0.3
  ionicons: ^0.2.2
  heroicons: ^0.11.0
  substring_highlight: ^1.0.33
  cross_fade: ^0.5.0
  flutter_holo_date_picker: ^2.0.0
  chips_choice: ^3.0.1
  responsive_navigation_bar: ^5.0.2
  #auth
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^6.0.4
  cached_network_image: ^3.4.1
  image_picker: ^1.0.7
  #wave dalgali ses kayıt
  audio_waveforms: ^1.3.0
  #wave dalgali ses dinleme urlden
  waved_audio_player: ^1.3.0
  audioplayers: ^6.5.1
  flutter_localization: ^0.3.3
  intl: ^0.20.2
  devicelocale: ^0.8.2
  #notifications
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  purchases_flutter: ^9.9.7
  purchases_ui_flutter: ^9.9.7
  url_launcher: ^6.3.2
  package_info_plus: ^8.1.1
  sign_in_with_apple: ^7.0.1
  flutter_popup: ^3.3.9
  random_string: ^2.3.1
  shimmer: ^3.0.0
  share_plus: ^10.1.2
  wave_player: ^0.0.4
  smooth_page_indicator: ^2.0.1
  gradient_borders: ^1.0.2
  rive: ^0.14.0
  speech_to_text: ^7.3.0
  record: ^6.2.0
  ficonsax: ^0.0.3
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/
    - assets/icons/
    - assets/
    - assets/langs/tr.json
    - assets/langs/en.json
    - assets/langs/de.json
    - assets/langs/it.json
    - assets/langs/fr.json
    - assets/langs/ja.json
    - assets/langs/ru.json
    - assets/langs/es.json
    - assets/langs/ko.json
    - assets/langs/hi.json
    - assets/langs/pt.json
    - assets/langs/zh.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
